language: node_js

node_js:
  - "0.12"
  - "0.10"

env:
  - SASS_VERSION=3.4.6
  - SCSS_LINT_VERSION=0.38.0

before_install:
  - npm install -g grunt-cli
  - gem update --system

install: npm install

before_script:
  - gem install sass -v $SASS_VERSION
  - gem install scss_lint -v $SCSS_LINT_VERSION
  - grunt lint
  - grunt test
