language: node_js

node_js:
  - "0.12"
  - "0.10"

before_install:
  - npm install -g grunt-cli
  - gem update --system

install: npm install

before_script:
  - gem install scss_lint -v 0.38.0
  - grunt lint
  - grunt test
